apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
  selector:
    app: {{ .Release.Name }}-wordpress
